apiVersion: v1
data:
  example.conf: |-
    input { stdin { } }

    filter {
      grok {
        match => { "message" => "%{COMBINEDAPACHELOG}" }
      }
      date {
        match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
      }
    }

    output {
      elasticsearch { hosts => ["localhost:9200"] }
      stdout { codec => rubydebug }
    }
kind: ConfigMap
metadata:
  labels:
    name: logstash
  name: logstash-pipelines
  namespace: examples
