apiVersion: v1
data:
  pritunl.conf: |-
    {
      "debug": false,
      "bind_addr": "0.0.0.0",
      "port": 443,
      "log_path": "/var/log/pritunl.log",
      "temp_path": "/tmp/pritunl_%r",
      "local_address_interface": "auto",
      "mongodb_uri": "mongodb://pritunl:_3sbjfMZm3GOcfIu7c_bKdmzZuc_gO0Dgn6CfKbYMgk@pritunl-mongo:27017/pritunl"
    }
kind: ConfigMap
metadata:
  labels:
    name: pritunl
  name: pritunl
  namespace: pritunl
